### ISSUE TITLE
Add properties to edges?

### ISSUE THREAD

**Issue by SimonEnsemble** [JuliaGraphs/LightGraphs.jl#1020]
I need to store graphs that have edges:

```
struct Edge
    src::Int
    dst::Int
    direction_traversed::Tuple{Int, Int, Int}
end
```
and I need `add_edge!(graph, Edge(1, 2, (1, 0, 0)))` and `add_edge!(graph, Edge(1, 2, (0, 0, 1)))` to actually add two edges to a directed graph that are considered different even though source and destination are the same. But walking through the graph to find cycles, that should depend on the source `src` and destination `dst` only, as in the usual algo in `LightGraphs.jl` currently.

[I will use the property `direction_traversed` to then keep track of which unit cell I arrived at as I walk through the graph of connected segments in a crystal as found via the cycle-finding algo. See Fig. 1 [here](https://pubs.acs.org/doi/10.1021/ct200787v).]

It seems that `MetaGraphs.jl` does not do this. Is there a way to do this in `LightGraphs.jl`?

Thanks a lot for your help.

**Comment by simonschoelly** [comment]
I think what you want is called a multigraph (a graph that can have multiple edges between the same set of vertices). `LightGraphs` currently does not have something like that. I see two ways of faking something like that:
1) Using `MetaGraphs`, attach a vector as a property to each edge. Then in the property associated to each edge you would track the multiple instances of that edge, i.e in your example edge `(1,2)` could probably have the attached the vector `[(1,0,0), (0,0,1)]` as a property. 

2) If a source `s` should have two edges going to the same destination `d`, then add two artificial vertices `v1, v2` to the graph, and replace the edge `(s, d)` with  four edges `(s, v1), (s, v2), (v1, d), (v2, d)`. I.e you would transform
```
                     v1 
                    /   \
s -- d    =>       s     d
                    \   /
                     v2
```

Both approaches have some drawbacks, that depend on what you exactly want. Otherwise you probably have to use a library for another language such as `NetworkX` for Python - that library has support for multigraphs.

**Comment by SimonEnsemble** [comment]
@simonschoelly Thank you, idea #2 is very clever!

So in my example above, instead of:
```
add_edge!(graph, Edge(1, 2, (1, 0, 0)))
add_edge!(graph, Edge(1, 2, (0, 0, 1)))
```

I create artificial vertices which each have a property associated with them:
```
graph = DiGraph(2) # for my two REAL vertices
vertex_to_direction = Dict{Int, Union{Nothing, Tuple{Int, Int, Int}}}(1 => nothing, 2 => nothing) # these real vertices have no direction associated

# add artificial vertices
add_vertex!(graph) 
vertex_to_direction[3] = (1, 0, 0)
add_vertex!(graph)
vertex_to_direction[4] = (0, 0, 1)

# add edges but first pass through artificial vertices
#  1 --> 2 w./ direction (1, 0, 0)
add_edge!(graph, Edge(1, 3))
add_edge!(graph, Edge(3, 2))
#  1 --> 2 w./ direction (0 ,0, 1)
add_edge!(graph, Edge(1, 4))
add_edge!(graph, Edge(4, 2))
```
and so now I can look for simple cycles and these simple cycles will involve the same sequence of 'real' vertices, just that the artificial vertices will be every other step along the cycle.
