### ISSUE TITLE
Feature request: Eulerian trails and circuits

### ISSUE THREAD

**Issue by simonschoelly** [JuliaGraphs/LightGraphs.jl#1061]
I surprised that LightGraphs doesn't have that yet. Should no be to difficult to implement.

**Comment by ChamanAgrawal** [comment]
Hi! I am new to Julia, This issue seems interesting to me and I wanted to start my Julia journey with this. Can I work on this? Any advice?

**Comment by sbromberger** [comment]
@ChamanAgrawal :
- In general, you may work on any open issue you'd like! We welcome all contributors, especially new ones.
- Please read through [the contributor guide](https://github.com/JuliaGraphs/LightGraphs.jl/blob/master/CONTRIBUTING.md) and make sure you understand it. Feel free to ask any questions; we're a pretty friendly bunch. We also hang out on Slack, in the #graphs channel.
- Open up a PR as soon as possible, and iterate as much as you want. This gives us an opportunity to review your work in progress, and we can offer suggestions as you go.
- Make sure you include documentation and comprehensive tests. We have a specific format for docstrings; most functions should serve as good examples.
- Ask here or in your PR if you need any help.

Welcome! I'll go ahead and assign this one to you so that others know you're working on it and can contact you if they'd like to collaborate.

**Comment by ChamanAgrawal** [comment]
I am working on this.

**Comment by ChamanAgrawal** [comment]
Bump, this issue is hanging due to #1080 , just wanted to know the status :)
