### ISSUE TITLE
Go Forward direction: include an API guarantees section in docstrings

### ISSUE THREAD

**Issue by sbromberger** [JuliaGraphs/LightGraphs.jl#1117]
Following a really great discussion with @jpfairbanks, I think it's important that we specify the API guarantees for each function in LightGraphs. This means, for example, when we have a function that currently returns a vector, but we really just want an iterable (for example, `neighbors()`), we can make the API guarantee that the function returns an iterable. This will allow us to change the return type of the function without requiring a major release.

The idea here is that we would start documenting the API guarantees now, and then when we're at some critical mass, we'd release LightGraphs 2.0 so that anyone using 1.0 would have the old non-guarantees, but anyone using 2.0 would be constrained / empowered by the guarantees. This would also allow us to implement graph structures that might return a `Set` for neighbors, as an example, since that might be the native representation.

Currently, since there are no guarantees specified for most (any?) functions, there may be confusion as to what to expect from one of these functions.

#1116 may be the first one to get this treatment.

**Comment by mcognetta** [comment]
This would also be nice for the SimpleGraphs generators. I would be happy to help with it.

I have been working on a package for generic versions of the generators that we have implemented and having such guarantees would make testing much easier since the "indexing" of the graph would be guaranteed independent of the graph type.
