### ISSUE TITLE
Return order of vertices visited by DFS

### ISSUE THREAD

**Issue by Hofsmo** [JuliaGraphs/LightGraphs.jl#1272]
Hi,
I have problem where it is convenient to iterate from a source vertex `s` over a tree `t` given by `t = dfs_tree(G, s)`. If `s=1` this can easily be done by the following code:
```
t = dfs_tree(G, s)
for vertex in vertices(t)
   do_stuff(vertex)
end
```
However, if `s != 1` this does not work, since the fist vertex given by `vertices` is 1.  I guess my problem could easily be solved by having a `dfs_tree` function that also returns the order of which the vertices were visited. Is that something that would be of interest for other people too, or is my problem too specific?

Cheers Sigurd

**Comment by sbromberger** [comment]
The way I'd normally suggest doing this is to take the general DFS algorithm and write a custom function with the visitors you want. The algorithm in [`dfs_parents()`](https://github.com/JuliaGraphs/LightGraphs.jl/blob/master/src/traversals/dfs.jl#L102) is probably a good starting place.

We used to have custom visit functions for BFS and DFS, but that was back in the pre-1.0 days when they added overhead. We might want to revisit adding the visitor capability back into BFS and DFS since there's been some work on call overhead in Julia over the last couple of years.

cc @jpfairbanks @simonschoelly

**Comment by Hofsmo** [comment]
Thanks for the suggestion.
I think I will implement a custom DFS function as you suggested, but it would definitively be nice with a DFS algorithm that accepted a custom visitor function. I am working with power systems and there are many cases where iterating the network using DFS or BFS could be quite useful.

Cheers Sigurd

**Comment by sbromberger** [comment]
If you wanted to do some benchmarking with implementing visitor functions (use an `@inline` directive and make the function do nothing by default), that'd be a big help. If we can show that having a NOP visitor function does not impact performance, it's a straightforward PR.

**Comment by Hofsmo** [comment]
Thanks, I will give it a shot next week. I am quite new to Julia, so I am not guaranteeing anything ;)

Cheers Sigurd

**Comment by sbromberger** [comment]
Ref #1278 - benchmarks look good for BFS. Want to try DFS next week? You can use my ugly code as a reference.

**Comment by sbromberger** [comment]
@Hofsmo did you get a chance to work on this? If not, I can do it, but I wanted to give you an opportunity to contribute if you had the time/desire to do so.

**Comment by sbromberger** [comment]
I've added DFS-based traversals to #1278.
