### ISSUE TITLE
Explore ways to eliminate/reduce random test failures

### ISSUE THREAD

**Issue by birm** [JuliaGraphs/LightGraphs.jl#1302]
Some of the non-deterministic methods have tests that fail sometimes.
This has been noticed in #886 for label propagation and in #534 in spectral (though that seems to have been resolved).

I'm sure there are other methods for which this happens too.

**Comment by birm** [comment]
One solution is to seed the tests themselves to avoid unpredictability. Another is to identify which random values(s) cause the methods to behave differently and, if the different results are wrong or otherwise undesired, avoid/fix that situation.

**Comment by sbromberger** [comment]
There's a third option: fail after "n of m" tests fail. This has the advantage of handling randomness with probability, but has the disadvantage of making the test suite more complex (and longer in the worst case).

cc @simonschoelly @jpfairbanks since I think they were involved in the original discussion.

**Comment by birm** [comment]
I think we want to keep this open for now. So that we don't have to, is a retry n times, expect >m successes loop or macro around certain tests reasonable? Does this still apply with 2.x?
