### ISSUE TITLE
[BUG] DFS is horribly broken

### ISSUE THREAD

**Issue by sbromberger** [JuliaGraphs/LightGraphs.jl#1312]
**Description of bug**
Experimental DFS is broken (as is the nonexperimental `topological_sort_by_dfs()`. It takes way too long to traverse; there is some massive problem with the algorithm.

**How to reproduce**
Create a `star_graph(100_000)`. Run DFS. Note that it takes SECONDS to work.

**Expected behavior**
This should be much faster.

**Actual behavior**
This is too slow.

**Code demonstrating bug**
If applicable, provide a minimal working example of the bug.

**Version information**
LG master

**Additional context**

**Comment by alimamdouh212** [comment]
i think the problem is that we rescan every neighbours array, instead of resuming from the last index we were in the last time were in the node, the star graph is the perfect example for that problem, only one neighbours  that we care about, but we rescan it over and over which lead to O(n^2) .

that code will avoid this problem 

`function dfs2(g::AbstractGraph{T},source) where{T}
s=Vector{}([])
ptr=one(T)
visited=falses(nv(g))
parent=zeros(T,nv(g))
push!(s,(source,0))
while !isempty(s)
    v,_=s[end]

    vneighbors=outneighbors(g,v)
    while ptr <= length(vneighbors)
        u=vneighbors[ptr]
        if visited[u]==false
            
            push!(s,(u,ptr+1))
            
            visited[u]=true
            parent[u]=v
            
            break
        end
        ptr+=1
    end
    if ptr>length(vneighbors)
        _,ptr=pop!(s)
      else
        ptr=1
    end

end
return parent
end`

because it remember where we were in the  neighbours array the last time we were in that node

**Comment by sbromberger** [comment]
Fixed in #1330 via https://github.com/JuliaGraphs/LightGraphs.jl/pull/1330/files#diff-b259d5b41b81a584f831146116a78501
