### ISSUE TITLE
betweenness_centrality docstring

### ISSUE THREAD

**Issue by hayd** [JuliaGraphs/LightGraphs.jl#145]
So, this is because

```
g: SimpleGraph
    A Graph, directed or undirected.
weights: AbstractArray{Float64, 2}, optional
    Matrix containing the weight associated with each edge (i,j)
    `ω[i, j]` is the weight between vertices `i` and `j`.
    If no weights are specified, shortest paths are computed using equal
    weights. If values are missing, they are assumed equal to `1`.
    *Advice* Use sparse matrices for better performances.
```
![screen shot 2015-08-18 at 17 48 16](https://cloud.githubusercontent.com/assets/1931852/9346436/940f5d10-45d1-11e5-8ed8-8e19c5e6da63.png)

also on rtd https://lightgraphsjl.readthedocs.org/en/latest/centrality/

I'm not sure this is a Markdown bug (although I know that Markdown does not yet parse newlines properly nor does it do nested lists - IIRC that's on the TODO list). meh

---

Perhaps easiest/cleanest to just do:

```
##### g: SimpleGraph
A Graph, directed or undirected.
##### weights: AbstractArray{Float64, 2}, optional
Matrix containing the weight associated with each edge (i,j)
`ω[i, j]` is the weight between vertices `i` and `j`.
```
Honestly I kind hate all these sections...

---

*Note: Writing up some quick slides in case I've been roped into presenting at the next meetup!*

**Comment by sbromberger** [comment]
@hayd - anything I can do to help close this out?

**Comment by hayd** [comment]
Sorry, I've been away.

I think easiest way is to use the snippet above. Docile may offer a nicer/more flexible DSL soon... I think using a table was also mooted for parameters, thoughts?

**Comment by sbromberger** [comment]
@hayd a more general question: the next version of LightGraphs will be 0.4-only. Is there anything we can remove from the existing codebase to streamline it given the upcoming doc changes in 0.4-release?

**Comment by hayd** [comment]
>  the next version of LightGraphs will be 0.4-only

I'm going to sulk a little about this (everyone is doing it :p )

You can remove references to Docile in the src/ and as a dependancy.

**Comment by sbromberger** [comment]
> I'm going to sulk a little about this (everyone is doing it :p )

Sorry. There are a few really good reasons for this. First is that we're moving to a sparse matrix internal storage (from an adjacency list that was vector-of-vectors) and efficient sparse boolean operations aren't being backported to 0.3 as far as I know, so things like edge insertion become really inefficent. Second is that I'm tired of `@compat` statements everywhere and would like to start clean. Finally, it's really a pain to have to test 2 different versions, but it's necessary. Now that 0.5-dev is out, we're going to have to maintain compatibility with it as well, and supporting three versions (0.3, 0.4, and 0.5) is just gonna be too time-consuming.

The good news is that v0.4 of LightGraphs (mirroring v0.4 of Julia) will offer the beginnings of parallelism. Betweenness centrality and Dijkstra shortest paths are first, and it's nothing short of amazing what we can do. We're now faster than graph-tool in both single- and multi-core, and since igraph is only single-core at the moment, we're faster than it as well (though its single core performance on betweenness is still significantly better than LightGraphs so it's an unfair comparison but I'll make it anyway). The "sparsemx" branch (and #150) will keep you abreast of latest developments there.

Thanks for the info. I'll go ahead and remove the Docile references and dependency. This is good because we're having to add a new entry to `REQUIRE` (@madeleineudell's ParallelSparseMatMul package gives us really nice shared sparse matrices) and I'd really like to keep the number of dependencies as low as possible.

Why sulk, though? LG v3.3 will still continue to work on Julia 0.3, and we get a very nice backend change to LG in v0.4 that will make it even faster on multicore systems. Plus, we have excellent documentation! :)

**Comment by hayd** [comment]
Awesome!! I'm not really sulking. I'm just still in the python 2/3 mindset where supporting both is just the done thing (and a damn sight fiddlier that Compat). Julia is totally not the same beast, so I just need to get over it. Everyone will be using 0.4 so it's all good.

These performance enhancements are exciting.

Off topic, but have you tried Mux yet (I wonder how the performance of that compares to Go or similar), I trying to hack out something with routes/templates/mvc on top of it (I suspect I'm not the only one).

**Comment by sbromberger** [comment]
I haven't tried Mux out in a while. I should get back into web services though. Coupled with things like Escher, I think visualization of LightGraphs via HTTP is gonna be big.

**Comment by sbromberger** [comment]
Closing out since I think we've fixed this....
