### ISSUE TITLE
Bipartite incidence matrix

### ISSUE THREAD

**Issue by jfb-h** [JuliaGraphs/LightGraphs.jl#1475]
Is there a way to compute the (node-to-node) incidence matrix for a bipartite graph? I looked into the codebase but couldn't find anything.

I implemented the following hack which seems to do the job but if there's an 'official' way I'd rather use that: 

```
function bipartite_incidence_matrix(g::AbstractGraph)
	idx = Bool.(bipartite_map(g) .- 1)
	A = adjacency_matrix(g)
	return A[idx, .!idx] 
end
```

**Comment by jpfairbanks** [comment]
This seems like a fine way to do it. LG doesn't have special support for what I call *bipartitioned* graphs, which are graphs that are stored as two sets of vertices (red,black).

 When I've worked with spectral methods for bipartite graphs in the past, we would number the vertices `[1:nred, nred+1:nred+nblack]` and then the adjacency matrices you are computing would be the upper right quadrant of the regular adjacency matrix with that vertex ordering. The property of being a bipartitioned undirected graph means that all the nonzeros are in the off diagonal quadrants which are transposes of each other.

I'd like for more specialized tools to arise for handling these special kinds of graphs, but that is kinda out of scope for LG itself. Although the LG API should be used as much as possible so that the tools are mutually compatible.

**Comment by jfb-h** [comment]
I agree, a `BipartiteGraph` Type would be nice to have. As I only need the incidence matrix to project to unipartite, my hack will do for the moment.
