### ISSUE TITLE
Ordering edges

### ISSUE THREAD

**Issue by timholy** [JuliaGraphs/LightGraphs.jl#1480]
I'm contemplating making a time investment in some computational chemistry tools for Julia, and LightGraphs is the obvious choice for representing molecular structure. However, [chirality](https://en.wikipedia.org/wiki/Chirality_%28chemistry%29) appears to pose a challenge. The major [conventions](https://en.wikipedia.org/wiki/Cahn%E2%80%93Ingold%E2%80%93Prelog_priority_rules) appear to require that one be able to order the edges of a node.

In contrast with #986, I'd only need ordering among the edges from the same node. I could imagine just using the vertex ordering and inserting the edges in an order that implicitly encodes the chirality (e.g., the third edge encodes the atom that is clockwise from the 2d plane spanned by the first two edges, looking from the source to the target of the first edge), but:
- I don't know whether that ordering would be guaranteed to be preserved under graph manipulations
- I would need to be able to guarantee certain API features, such as two labeled graphs representing mirror-image stereoisomers do not compare as equal, but do compare as equal if they are the same stereoisomer.

Thoughts on the feasibility of these requirements? CC @caseykneale.

**Comment by caseykneale** [comment]
Great idea. But yes, I see the difficulty. So I love the idea of doing some comp. chem. in Julia, and also the idea of ordered edge's being native to a graph type. The issue with this, that I see anyways, is a lot of algorithms will not consider this ordering unless we enforce it.

Consider a simple template matching problem via a min distance graph walk from one moeity to another. Say we want to see if two graphs have an isomorphic backbone or something. Assume there are two enantiomers who have a chiral component in the backbone with ordered edges(clockwise, or anti). The walk would be the same hops, and even the same nodes would be visited - yet different chemical behaviour.  The issue isn't with the encoding then - I think it's with the canned algorithm?

If we introduced an implied "weighted" ordering scheme. 0, 1, 0, -1. That might work? Where 0 means "in the plane" and 1/-1 means out of the plane or semantically speaking CIS/Trans(still in plane but different ordering)? So if we crawled from one chain to another we would get different weights... Basically we are trying to encode 3 space to 2, means we need an additional abstraction somewhere.

When I was perusing this issue - I came up with some alternatives, none of them were "healthy"... Namely:
* Use a MetaGraph(https://github.com/JuliaGraphs/MetaGraphs.jl) and type each edge. This is not generic... 
* Enumerate edges via their position. Hard to make meaningful as above...
But depending on how the graph is read maintaining that understanding may best be done via proper encoding (as in - how we properly define stereochemistry). 

This is probably some form of open problem or another. I would love to know how other's are approaching it, but a quick google search hasn't given anything very useful - yet. I'll keep thinking...

**Comment by caseykneale** [comment]
Found a brief overview of the issue and how some people have chosen to handle it: https://onlinelibrary.wiley.com/doi/abs/10.1002/9783527618279.ch8

**Comment by etienneINSA** [comment]
For `SimpleGraphs`, I don't know what are exactly the specifications, but I think you can take that :
- vertices of a graph `g` are guaranteed to be a range from `1` to `nv(g)`. 
- neighbors of a vertex are guaranteed to be ordered.

The only pitfall is if you remove vertices. This is because `SimpleGraphs`maintains the vertex set to a range of integers, even upon deletions of vertices. So the name of a vertex can change if some vertices with a lower name are deleted. 
So if you want to handle vertex deletions, you need an other graph type. You might want to check [VertexSafeGraphs.jl](https://github.com/matbesancon/VertexSafeGraphs.jl). It is built on top of a `SimpleGraphs`, so the second assumption on `SimpleGraphs`still hold.

If your library rely a lot on modifying graphs, you might want to use a type of graph optimized for such insertions and deletions. This is because `SimpleGraphs` uses Arrays for storing the neighbors. So, `insert` is used when adding new edges, and the removal of vertices is even worse. I'm not aware of any implementation of dynamic graphs in julia, so you might need to implement your own.

**Comment by sbromberger** [comment]
@timholy - was this resolved to your satisfaction, or do we need to keep the issue open for further discussion? Thanks.

**Comment by timholy** [comment]
I'm using [MolecularGraph.jl](https://github.com/mojaie/MolecularGraph.jl) these days which has its own internal graph package.

**Comment by sbromberger** [comment]
OK, thanks for the update.
