### ISSUE TITLE
Feature request: findall edges

### ISSUE THREAD

**Issue by lindnemi** [JuliaGraphs/LightGraphs.jl#1487]
I would like to use

```julia
g=star_graph(5)
findfirst( isequal(Edge(1,2)) , edges(g))
```

to get the linear Index of an edge. It seems that `keys(edges(g))` is not implemented.  My naive idea is that the keys should be indices from 1 to ne(g). Is there a specific reason that this doesn't work at the moment?

**Comment by sbromberger** [comment]
Unfortunately, this is not possible as there is no index for edges in LightGraphs / AbstractGraphs since we make no guarantees of edge ordering. The closest we come is with SImpleGraphs, but even then I don't believe we publish that as a guarantee.

You're free to collect the edges and create your own ordering, but you should really think of the edges of an AbstractGraph as an unordered set.

**Comment by lindnemi** [comment]
Alright, thank you for the clarification! Is there a guarantee that `edges(g)` will iterate over the edges in the same order on separate calls?

**Comment by sbromberger** [comment]
> Is there a guarantee that edges(g) will iterate over the edges in the same order on separate calls?

There's no explicit guarantee of that but the current implementations of SimpleGraphs and SimpleWeightedGraphs will do this.

**Comment by lindnemi** [comment]
ok thank you again :+1:

**Comment by sbromberger** [comment]
Just as an aside: there is nothing preventing you from making your own graph structure with edge indexing :) As long as you implement all the functions in `interface.jl`, things should just work (and if they don't then that's probably a reportable bug).
