### ISSUE TITLE
DISCUSSION: new version of LG will be for Julia 0.4 (and higher) only.

### ISSUE THREAD

**Issue by sbromberger** [JuliaGraphs/LightGraphs.jl#183]
I've been working on a `v4` branch for a bit and I think it's ready to merge. My thought is that it's been a pain to support 0.3 and 0.4 (which we've done since we started), and that I'd like to cut the 0.3 cord now that 0.4 has been out for a bit. To this end, here's what I propose:

1) sometime in the next week we tag a final version of LG that passes tests on 0.3
2) I merge the `v4` branch (this has some fixes and gets rid of Compat.jl, among other things)
3) further development happens on master, which is now 0.4-only.

In the event there's a "critical" bug we can always backport it, but all new development should be in the 0.4-specific master.

Thoughts?

explicit cc @jpfairbanks @hayd @pranavtbhat

**Comment by jpfairbanks** [comment]
Ref: PR #169 
I think this is reasonable. We should also add 0.5 to the test suite.

**Comment by sbromberger** [comment]
Yes, absolutely re: 0.5,  but that may put us right back to supporting two different versions of Julia (which was a pain). Still not sure how we'd do it. `@compat` is not ideal.

**Comment by jpfairbanks** [comment]
Is it easier to support the latest stable and master of JuliaLang or to support stable and then when the release candidate comes out, we hurry to get everything updated? 

I think that CI and compat make it easier to support both versions. 

If everyone decides not to support the latest development version, then none of the packages will work on 0.5 so no one will be able to use it which will hurt development of the language ecosystem.  I don't want to get into the same situation I had with scientific python a few years ago. I couldn't write python 3 because scipy didn't  work yet but the port of scipy was too hard because the languages had diverged sufficiently that it was a lot of work to update to it. They eventually bit the bullet but it took way too long. 

If we just keep up with the small changes in 0.5 we won't need to do a big port in the future. We should pull our weight and support the ecosystem by supporting 0.5 now.

**Comment by sbromberger** [comment]
Yeah - we need to ensure building on master. I was sort of hoping we wouldn't need to do anything special but you're right. I didn't really have the same issue with 0.3->0.4 since I was developing on 0.4 (master) anyway. It was a pain to try to get it working under 0.3 but I guess that's unavoidable.

**Comment by sbromberger** [comment]
I'm going to tag a final 0.3-compatible release today, and then commit `v4`.

**Comment by sbromberger** [comment]
Closing this out since 0.4.0 is now pending METADATA merge.
