### ISSUE TITLE
export unsafe functions

### ISSUE THREAD

**Issue by CarloLucibello** [JuliaGraphs/LightGraphs.jl#193]
While the default baheviour should be the safe one, I'm in favor of giving users the possibility to fine tune their code

**Comment by sbromberger** [comment]
See https://github.com/JuliaGraphs/LightGraphs.jl/pull/103#issue-97774232 - I'm disinclined to export the methods. Users who need them can always call them explicitly, but we want to discourage their use in day-to-day activity.

**Comment by CarloLucibello** [comment]
the fact that you have to call `unsafe_add_edge` instead of `add_edge` seems to me discouraging enough, while not exporting and not documenting the function substantially means hiding it form the user

**Comment by jpfairbanks** [comment]
The way I see it is that exports are a contract that we support use of this
function with a stable api into the future.  We haven't formally discussed
what "support" means and we should certainly get on top of that as the
project grows.

Every function should be well documented. I think it's appropriate to have
a section of the manual on nonexported functions. We can say that some
functions have nonexported versions that are more performant but might have
a less stable interface. For example the connected_components! function
uses a label array rather than an array of arrays. I would have no fear of
changing that interface because it is not exported. However
connected_components is exported and I would not want to change the return
type without depreciation warnings and such.

We should hash out proper criteria for the exporting of functions. This
should go along with a discussion of versions and documentation.
