### ISSUE TITLE
Stochastic Block Model has quadratic run time complexity

### ISSUE THREAD

**Issue by jpfairbanks** [JuliaGraphs/LightGraphs.jl#212]
For small dense SBMs the current code is sufficient.
For large sparse SBMs, the sampling can be done in E[ne(g)] time.
pseudo-pseudocode:
```
Use the sizes and probabilities to compute the E[ne(g)];
edgecount ~ poissson(E[ne(g)])
while ne(g) < edgecount
    i,j = rand(1:n, 1:n)
    r = rand(0,1)
    if r < P[i,j]
        add_edge(g,i,j)
    end
end
return g
```

These will be important for understanding the performance of community detection routines.

**Comment by CarloLucibello** [comment]
definitely this should be done

The implementation its slightly more involved than the one you showed above. Since you have two probabilities, one for diagonal blocks and one for off-diagonals, two random numbers have to be generated according to two binomial distributions, and edges added in a consistent way

I can take care of this

**Comment by CarloLucibello** [comment]
the same enhancement should be made for the Erdo Renyi generator

**Comment by sbromberger** [comment]
@CarloLucibello if you're ready to work on E-R, please open up a tracking PR.

**Comment by CarloLucibello** [comment]
Erdos Renyi is alright now, after the recent pull requests
