### ISSUE TITLE
revisit discussion around removing edge sets

### ISSUE THREAD

**Issue by sbromberger** [JuliaGraphs/LightGraphs.jl#221]
cc @CarloLucibello @jpfairbanks 

Sorry it's taken me so long to come around. I would like to discuss removal of edge sets from LightGraphs. Here's why my thinking has changed:

1) as it turns out, checking for an edge in a Graph is roughly O(d), where d is the average degree.
2) we can get this down to `log(d)` if we order the adjacency vectors. I don't know what cascading performance issues there might be, but in any case,
3) when d is "reasonable" (that is, < 2500) the difference between set membership testing and unordered vector membership testing is pretty much equivalent (and measured in nanoseconds). When we get up to degrees around 50k, we start seeing roughly 10x difference between the two.
4) This change will save ~128 bits per edge, or roughly half the space of the graph.

So - thoughts? @CarloLucibello - could you resurrect your change to remove edge sets so we can do some performance testing on reasonable graphs?

ref: #163

**Comment by sbromberger** [comment]
And credit where credit is due: as usual, @jpfairbanks (in https://github.com/JuliaGraphs/LightGraphs.jl/pull/163#issuecomment-149566365) is, again, about two weeks ahead of my thought process.

**Comment by CarloLucibello** [comment]
1) Why you say that checking for an edge existence in the Set is O(d)? My implementation with iterators was O(d), and I noticed a big performance hit when checking existence in complete graphs. 

2) keeping the adjacency vertex sorted is an expensive operation, we would pay dearly in the graph construction what we gain in the search. If we want to keep things sorted we'd better use linked lists, but this complicates things

3) All that said, I'm still in favor of eliminating the edge set, because it would be more memory and time efficient in most cases and because very large and very dense case are not a realistic use case scenario

**Comment by sbromberger** [comment]
Checking for edge existence is O(d), I think, because `e in g` can simply be `dst(e) in fadj(g, src(e))`, which is O(1) to get to `fadj(g, src(e))` and O(`degree(g, src(e))`) for the membership test.

In any case, here are some current memory calculations with the edge sets:

Memory cost of Graph (bytes): 376 + 16(nv) + 32(ne).
Memory cost of DiGraph (bytes): 376 + 16(nv) + 16(ne).

**Comment by sbromberger** [comment]
On a related note, please see #222.

**Comment by jpfairbanks** [comment]
> 2) keeping the adjacency vertex sorted is an expensive operation, we would pay dearly in the graph construction what we gain in the search. If we want to keep things sorted we'd better use linked lists, but this complicates things

For construction, one can sort the edges to insert `(i,j) < (k,l) if i <= k and j < l` before inserting them in order to improve graph construction performance. You might want to do this even if the fadjlist isn't sorted  for locality anyway.

**Comment by jpfairbanks** [comment]
@sbromberger 
> 3) when d is "reasonable" (that is, < 2500) the difference between set membership testing and unordered vector membership testing is pretty much equivalent (and measured in nanoseconds). When we get up to degrees around 50k, we start seeing roughly 10x difference between the two.

What exactly are you measuring?

I ran this experiment:

```julia
S = Set{Int}()
for i in 1:10^4
       push!(S, i)
end
v = collect(1:10^4)
 
@time for i in 1:10^5
       b = (i in S)
end  
0.005316 seconds (99.53 k allocations: 1.521 MB)
@time for i in 1:10^5
       b = searchsorted(v, i)
       end
0.023686 seconds (414.73 k allocations: 9.931 MB, 16.48% gc time)
@time for i in 1:10^5
       b = (i in v)
end
0.518794 seconds (99.53 k allocations: 1.521 MB)
```
Through the power of asymptotics O(n) > O(logn) > O(1)!

**Comment by sbromberger** [comment]
```
julia> a = rand(Int,5000);

julia> b = Set(a); length(b)
5000

julia> @time 65 in a
  0.000008 seconds (4 allocations: 160 bytes)
false

julia> @time 65 in b
  0.000004 seconds (4 allocations: 160 bytes)
false
```

**Comment by CarloLucibello** [comment]
> julia> @time 65 in b 0.000003 seconds (4 allocations: 160 bytes) false 
> julia> @time 65 in a 0.000040 seconds (4 allocations: 160 bytes) false
well that's a factor ~10 difference, while james was observing for the same experiment, but doubling the length of the edgeset, a factor ~100 (of which a factor 2 is due to the doubling and a factor 5 is unexplained). Anyway with such low times it is better to have multiple repetition of tests as james did then doing a single trial.

I think  that the best benchmark would be to test has_edge on the largest and densest *real* graph we have at our disposal, real in the sense that they are not artificially constructed for this particular test. 

I'll try to resurrect the edge_iterators

**Comment by sbromberger** [comment]
Well, ultimately this comes down to a design decision: do we want to have decreased memory at the expense of less efficient edge membership checking, or do we want to have fast membership checking at the expense of duplicate data? 

My tests show that when you're checking membership of edges whose source vertices have degrees < 2500, there is no performance advantage to having the edge sets. It's when you get degrees greater than 50000 that you start seeing potentially large delays.

to @CarloLucibello's point: how realistic is it that you will have graphs with degrees approaching 50k? Most of the ones I'm working on are hard-limited to around 250.

**Comment by CarloLucibello** [comment]
In my work as a physicist I didn't ever work with graphs with max degree
greater then ~100 nodes. I think it is quite safe to assume that if in some
large graphs one has nodes with degrees ~50k then there could be only a few
of them, so that has_edge becomes slow only when looking at those nodes.

By the way we can have has_edge check for the existency of the edge in
adjlist of the node with smaller degree. In this way the only slow checks
would be that on edge beetween nodes which both have very high degree



2015-11-07 11:45 GMT-05:00 Seth Bromberger <notifications@github.com>:

**Comment by jpfairbanks** [comment]
Having average degree that high is unrealistic but having a single vertex with degree O(n) or O(sqrt(n)) is not unrealistic in scale free networks. @sbromberger your neighbor Roger Pearce has done a lot of research in the distributed memory setting on data structures that are optimized for scale free networks.

We might want to handle low degree vertices and high degree vertices differently. This will become more important once things are parallelized.

**Comment by sbromberger** [comment]
> By the way we can have has_edge check for the existency of the edge in
adjlist of the node with smaller degree.

This is actually a really great idea, and would be O(1). That is, for an `Edge(s => t), we could check the minimum of `fadj(g,s)` and `badj(g,t)`.

**Comment by CarloLucibello** [comment]
>We might want to handle low degree vertices and high degree vertices differently. This will become more important once things are parallelized.

we could mantain an edgeset for each vertex with an high enough degree

**Comment by sbromberger** [comment]
> we could mantain an edgeset for each vertex with an high enough degree

then we might as well maintain the entire edgeset, no?

**Comment by sbromberger** [comment]
@CarloLucibello do you have code you can resurrect, or should we start from scratch? In the spirit of iterating early and often, I'd like to get something in soon and tag a version.

**Comment by CarloLucibello** [comment]
yeah, I can resurrect my code but it could take a little effort to rebase it. 

Moreover I'm working on abstracting the graph concepts (in the LightGraph spirit, that is not sacrificing performance and ease of use), end once I do that, we could easily compare the performance of graphs with and without the edge set.

So let's first merge the current PRs, then I'll commit the graph abstraction, and then I'll build a new graph type with the edge iterators instead of the edgeset

**Comment by sbromberger** [comment]
Ergh. I'm not sure I'm a fan of abstracting the graphs. This is what got Graphs.jl into trouble, and is better suited for a graph factory package like it than a graph implementation package. It's fine for testing but I don't think I want to introduce multiple ways of doing things / multiple types of graphs in LightGraphs.

**Comment by sbromberger** [comment]
Don't worry about rebasing - would you mind resubmitting the PR? I'll figure out the merge stuff.

**Comment by CarloLucibello** [comment]
done #230

**Comment by sbromberger** [comment]
Closing this out in favor of #231.
