### ISSUE TITLE
Implement random sampling without replacement for Graph(m,n)

### ISSUE THREAD

**Issue by jiahao** [JuliaGraphs/LightGraphs.jl#243]
While testing JuliaLang/julia#14112 I seem to have found a situation where generating a random graph with more edges than is theoretically possible hangs the constructor:

```jl
julia> Graph(10,45)
{10, 45} undirected graph

julia> Graph(10,46)
^CERROR: InterruptException:
 in call at random.jl:471
 in call at /Users/jiahao/.julia/v0.5/LightGraphs/src/randgraphs.jl:7
 in eval at ./boot.jl:263
```

I presume the code for adding enough edges tries to guarantee that the resulting graph has the exact number of edges requested, in which case this problem might be avoided with a check to see if `ne > nv*(nv-1) ÷ 2` and throw an error if true.

**Comment by sbromberger** [comment]
You're correct in your presumption.

It doesn't hang, really; what it's trying to do is create a complete graph by random selection of edges and it's getting stuck trying to "guess" the last one. Generally, for random graphs, you want to make sure that `ne << nv(g)*nv(g-1)/2`, otherwise you're going to have to wait a bit while the last randomly-generated valid edges are guessed.

We should probably error out in the case where we know it's impossible; however, the creation time will get longer and longer as ne approaches the maximum, so I'm not sure we can error out of those near cases if the person really wants to wait. Thoughts?

**Comment by jiahao** [comment]
So the issue is that you need to do sampling without replacement, but you are currently doing it by attempting to sample with replacement (since you do `rand(1:N)` and `N` never changes as you sample) and rejecting the sampled edge if it's already present. So that's why you end up in an infinite loop when asking for an impossible graph like `Graph(10, 46)`.

Instead, it would be better to use a sampling algorithm designed for sampling without replacement, such as Knuth's Algorithm 3.4.2S in TAoCP

<img width="564" alt="screen shot 2015-11-25 at 10 53 16 am" src="https://cloud.githubusercontent.com/assets/1732/11401901/f8bb8674-9362-11e5-84d2-33543f1a748b.png">

<img width="561" alt="screen shot 2015-11-25 at 10 53 36 am" src="https://cloud.githubusercontent.com/assets/1732/11401905/fcbfeb84-9362-11e5-85e1-08ae34ac1618.png">

or the more complex method of Vitter, 1985, which I have implemented [in this gist](https://gist.github.com/jiahao/19cee463d4a8334495e6) for generable iterables, but should be specializable to the case of the edge set of a graph.

**Comment by sbromberger** [comment]
That's a nice algorithm. I'll give it a shot this week.

**Comment by sbromberger** [comment]
So, the biggest drawback to Vitter's Alg D is that it doesn't work well for smallish 'n'. That is,

```
julia> x = 1:100_000_000;

julia> c = combinations(x,2)
Base.Combinations{UnitRange{Int64}}(1:100000000,2)

julia> randsubset(c,5)
```

is taking a very long time, where the existing algorithm, though currently flawed, takes almost no time at all.

**Comment by sbromberger** [comment]
Partially fixed via https://github.com/JuliaGraphs/LightGraphs.jl/pull/244

**Comment by sbromberger** [comment]
@jiahao here's some testing of the randsubset code. It's scaling linearly with the number of edges but the big drawback is that it appears to require the permuted values to be generated prior to sampling, which means it will be very inefficient for small selections relative to the current random sampling with replacement strategy:
```
function f(i::Int)
       x = 1:i
       c = combinations(x,2)
       return (length(c), @elapsed(randsubset(c,5)))
end

julia> f(10)
(45,1.6437e-5)

julia> f(100)
(4950,0.000672583)

julia> f(1000)
(499500,0.070571155)

julia> f(10000)
(49995000,5.504472433)
```

**Comment by CarloLucibello** [comment]
I think that implementing Vittel's algorithm here is much more inefficient that the method we are already using, since it would beat random edge addition only when `ne` is close to its potential limit and randomly selected pair of vertices is very likely to be already present in the graph. But we just avoid this problem sampling the complementary graph

**Comment by sbromberger** [comment]
agree with @CarloLucibello, especially now that we're doing graph complements for larger-density graphs. Will close out for now but am happy to reopen should we need to discuss further.
