### ISSUE TITLE
infinite dependency loop with JuMP

### ISSUE THREAD

**Issue by mlubin** [JuliaGraphs/LightGraphs.jl#267]
I was looking at making LightGraphs a dependency of JuMP as part of the automatic differentiation code, but this threw precompilation into an infinite loop and terrible things happened. Would it make sense to move the code here which (optionally) uses JuMP into another package?
CC @IainNZ @vtjnash

**Comment by sbromberger** [comment]
I'm actually not fond of the optional dependencies we've hacked into LG and would love to explore alternatives. The package has competing goals: on the one hand, we don't want to implement our own code if there's expert stuff already available; on the other, since LG is really designed to be a fundamental package, we don't want a huge `REQUIRE` list.

Open to any and all suggestions here. Whatever we do should be consistent, though: if we decide to move the JuMP code into a separate package, we should do the same with GraphMatrices and any other conditional deps we have.

**Comment by mlubin** [comment]
What about ``LightGraphsExtras`` for functionality which depends on external packages?

**Comment by jpfairbanks** [comment]
I'll raise the other alternative of putting the "fundamentals" in LightGraphsBase and the extras in LightGraphs.

So then Jump can require LightGraphsBase and LightGraphs can require LightGraphsBase and Jump. If LightGraphs reexports everything in LightGraphsBase then the end user doesn't need to change anything.

**Comment by mlubin** [comment]
That also works for me

**Comment by sbromberger** [comment]
I think I'd prefer the first approach (keeping LightGraphs as the "core" package). That way we can expand it without fear of going against the stated goal (that is, LightGraphsBase implies "just the core stuff") whenever we have new functionality that doesn't require additional packages.

**Comment by mlubin** [comment]
I ended up not needing LightGraphs, so there's less urgency at this point.

**Comment by jpfairbanks** [comment]
We can close this in favor of more general discussion at #278
