### ISSUE TITLE
Is there any way to pick out a subgraph with "initial" indexes?

### ISSUE THREAD

**Issue by Gickle** [JuliaGraphs/LightGraphs.jl#287]
Hi. I am currently doing my bachelor project using your LightGraphs package in it. And I have some problems, which I hope I can solve with your help.

So I have the undirected graph g. And it has N connected components. For example, I need to pick out certain connected component (e.g. k) as individual graph h. Suppose this k-th component is something like:
```
connected_components(g)[k]
1
13
15
17
...
```
If I use now 

`induced_subgraph(g, connected_components(g)[k])`

I will have the subgraph with vertices numbered as 1, 2, 3, etc. 

Is there any way to pick out a subgraph with initial (1, 13, 15, 17, etc) indexes of vertices? 

Sorry for my bad English (not my mother tongue). I shall be really grateful for any help. Thank you in advance.

EDIT: Or another option. For example, I remove one vertex. I can easily determine wether it lead to "crushing" of my graph (number of connected components before < number of connected components after). Also suppose I know which subgraph specifically have been "crushed". Is there any way to quickly learn how my subgraph have been "crushed" exactly? I mean I would like to know indexes of connected components to which my subgraph was "crushed" (again, sorry for bad English).

**Comment by sbromberger** [comment]
If I understand correctly, you'd like the induced subgraph to contain vertices with IDs [1,13,15,17]. This is not possible in LightGraphs, unfortunately. When you create a subgraph, the vertices are renumbered since vertices are represented as a range, not a set or list.

The good news, perhaps, is that the vertices are renumbered in order: that is, the new graph's "vertex #1" is the one that was first in the list you provided to `induced_subgraph`; number 2 is the second in the list, etc. Therefore, your example (with 1,3,15,17) would result in a 4-node graph with the following mapping:

| old vertex | new vertex |
------|-----
| 1 | 1 |
| 13 | 2 |
| 15 | 3 |
| 17 | 4 |
| ... | 5... |

Does this help?

**Comment by Gickle** [comment]
@sbromberger 

Yeah, I though so. Ok, I will try to find another solution then. Thanks!

**Comment by sbromberger** [comment]
When I have to do this, I just keep the array I've passed in. It contains a reverse mapping from new to old. If I need the other way then I create a dict.

**Comment by Gickle** [comment]
@sbromberger 

That might be useful advice actually. I think I can now find some quick method for solving my problem. Thanks again. I suppose this issue can be closed now.

**Comment by sbromberger** [comment]
OK - feel free to respond or create a new issue if you have additional questions. Thanks!
