### ISSUE TITLE
Cleaning up the PRs

### ISSUE THREAD

**Issue by sbromberger** [JuliaGraphs/LightGraphs.jl#290]
Hi all,

I'd like to clean up the PR list and am seeking opinions on the following general strategy:

If a PR has

1.  failed tests AND
1.  has not had an update in more than 30 days

it will be eligible for closing.

Any objections?

(As a related aside, please go through and close any PRs you're not actively working on. Thanks :))

**Comment by CarloLucibello** [comment]
- #277 is stucked because of the depencies problem, I wouldn't close it until we come up with a solution
- #263 this I think was simply not review, maybe @pranavtbhat could kindly rebase so that we could merge it
- #235  could me merged after a rebase and eliminating the mutual_information function (since it's not needed for graph operations) @afternone

**Comment by sbromberger** [comment]
Closing now that we've made some progress.
