### ISSUE TITLE
awkward beahviour of load

### ISSUE THREAD

**Issue by CarloLucibello** [JuliaGraphs/LightGraphs.jl#294]
it is always kinda surprising to me that load functions return a dict instead of a graph, as I would expect, so I often attempt to do something like
```
g = load(f, :graphml)
nv(g) #error
```
instead of the awkward, at least to me, 
```
g = load(f, :graphml)["Unnamed Graph"]
nv(g) 
```

Wouldn't be better for `load` to support  only the much more common operation of reading a single graph from a single file, and have something like `loadgraphs` to return a `Dict`?

If this won't be the case, what about changing  "Unnamed Graph" to "graph" and  "Unnamed DiGraph" to "digraph" to spare some typing and since it is easier to memorize?

**Comment by sbromberger** [comment]
See [previous discussion](https://github.com/JuliaGraphs/LightGraphs.jl/pull/258#issuecomment-162525515) :)

Bottom line: several graph file formats allow multiple graphs per file. We need a type-stable, consistent way of reading them (type stable = graph reads of a given format return the same type of object under all circumstances; consistent = all graph reads return the same type of object). The only real way to do this is to override `load()` so that, if a graph name is specified, it loads that graph; otherwise, it loads a dictionary of graphs. The way we do this for some graphs is that we default the name for the single load (see the NET file format):
```
function loadnet(f::IO, gname::AbstractString = "g")
```

I've never really liked "Unnamed *" for anything, and I'm ok with changing them, but if you decide to make a PR, please make it consistent.

**Comment by CarloLucibello** [comment]
>See previous discussion :)

ah ah ah, sorry, forgot about that

>I've never really liked "Unnamed *" for anything, and I'm ok with changing them, but if you decide to make a PR, please make it consistent.

will do. I'll leave this issue open as a reminder
