### ISSUE TITLE
Missing Dev and Docs guidelines

### ISSUE THREAD

**Issue by CarloLucibello** [JuliaGraphs/LightGraphs.jl#337]
Someone wants to take a stab at this?

**Comment by jpfairbanks** [comment]
How do these sound?

# Contributing

Here are some guidlines for contributing code to this project.

## Bug reports
If you notice code that is incorrect/crashes/too slow please file a bug report. The report should be raised as a github issue with a minimal working example that reproduces the error message. The example should include any data needed. If the problem is incorrectness, then please post the correct result along with an incorrect result.

Please include version numbers of all relevant libraries and Julia itself.

## Development guidelines.

- PRs should contain one logical enhancement to the codebase
- Squash commits in a PR
- Open an issue to discuss a feature before you start coding (this maximizes the likelihood of patch acceptance)
- Put type assertions on all function arguments (use abstract types, Union, or Any if necessary)
- If the algorithm was presented in a paper, include a reference to the paper (i.e. a proper academic citation along with an eprint link)
- Take steps to ensure that code works on graphs with multiple connected components efficiently.
- Correctness is a necessary requirement; efficiency is desirable. Once you have a correct implementation, make a PR so we can help improve performance.
- We can accept code that does not work for directed graphs as long as it comes with an explaination of what it would take to make it work for directed graphs.
- When possible write code to reuse memory
For example
```julia
function f(g, v)
    storage = Vector{Int}(nv(g))
    # some code operating on storage, g, and v.
    for i in 1:nv(g)
        storage[i] = v-i
    end
    return sum(storage)
end
```
should be rewritten as two functions
```julia
function f(g::SimpleGraph, v::Integer)
    storage = Vector{Int}(nv(g))
    return inner!(storage, g, v)
end

function inner!(storage::AbstractArray{Int,1}, g::SimpleGraph, v::Integer)
    # some code operating on storage, g, and v.
    for i in 1:nv(g)
        storage[i] = v-i
    end
    return sum(storage)
end
```
This allows us to reuse the memory and improve performance.

**Comment by sbromberger** [comment]
Also something encouraging `foo && return` short-circuit syntax.

**Comment by sbromberger** [comment]
@jpfairbanks I made some minor edits directly to your suggestion. It's great. Could you file a PR for this?

**Comment by CarloLucibello** [comment]
That was a quick! Very nice. Can we reopen this though, I want to add some guidelines for the docs too, and I could use this as a reminder.

Also, probably we will want the Contributing section to take its own page in the documentation
