### ISSUE TITLE
Documentation does not appear to be auto-building

### ISSUE THREAD

**Issue by sbromberger** [JuliaGraphs/LightGraphs.jl#435]
@MichaelHatherly sorry to pull you in, but I'm completely stuck. I've tried to model the setup on the one in Documeter.jl, but for some reason it's not working. Here's what's going on:

- docs appear to be created ok in master. When I run a manual `julia make.jl` things don't look strange.
- Travis looks like it's doing the right thing.
- However, the docs in the `gh-pages` branch are never updated. What you see in that branch (and at https://juliagraphs.github.io/LightGraphs.jl/latest) is old and I don't know how I got it.
- I don't seem to have anything other than `latest` in any case.

1) How does travis know to use `gh-pages`?
2) Is my setup correct? (I created the deploy keys even though the github documentation suggests that they can't be used for project pages). The LightGraphs.jl pages setup says 'build from gh-pages' - I tried switching that to 'master' and 'master/docs' and got 404's as a result.
3) How do I troubleshoot this?

Thanks for any advice / help.

**Comment by MichaelHatherly** [comment]
> sorry to pull you in

No prob.

> What you see in that branch (and at https://juliagraphs.github.io/LightGraphs.jl/latest) is old

The latest commit to `gh-pages` is based on https://github.com/JuliaGraphs/LightGraphs.jl/commit/829317bff2f97559edd3418a2c62b1d71da01a8a, which was made in the last day, so not terribly old. Does that docs build contain outdated content?

> I don't seem to have anything other than latest in any case.

Have you tagged any new releases since Documenter was added? If not, then there won't be any other docs other than `latest`. When you tag a commit travis should build and deploy to a `stable` and `<tag>` folder.

---

From what I can see the problem is:

By default Documenter will deploy the docs from the `nightly` buildbot. Travis is currently only testing the package on `release`. You'll need to either uncomment https://github.com/JuliaGraphs/LightGraphs.jl/blob/b38d1a7b1feda5bb838ac8110ac11c424f9b9d5f/.travis.yml#L9 or uncomment https://github.com/JuliaGraphs/LightGraphs.jl/blob/b38d1a7b1feda5bb838ac8110ac11c424f9b9d5f/docs/make.jl#L14. I think that should get everything building properly again.

**Comment by sbromberger** [comment]
Thanks! Let's see if this works :)

**Comment by sbromberger** [comment]
@MichaelHatherly sorry,  I chose option 2 ("uncomment https://github.com/JuliaGraphs/LightGraphs.jl/blob/b38d1a7b1feda5bb838ac8110ac11c424f9b9d5f/docs/make.jl#L14") and pushed to master. gh-pages isn't being updated at all. I'll try the first option now.

**Comment by MichaelHatherly** [comment]
Travis is failing with a missing `mkdocs` dependancy, namely `mkdocs-material`, so just change the `deps = ` line in `make.jl` to

```julia
deps = Deps.pip("pygments", "mkdocs", "mkdocs-material", "python-markdown-math"),
```

which should do the trick.

**Comment by sbromberger** [comment]
Weird - I didn't notice the travis failure. Sorry.

**Comment by sbromberger** [comment]
cool - it's working. Thanks again!
