### ISSUE TITLE
Randomized tests are occasionally failing

### ISSUE THREAD

**Issue by sbromberger** [JuliaGraphs/LightGraphs.jl#455]
I don't have a concrete example to reference, but it happened earlier with #454. This issue is to keep track of testing failures with randomized tests in randgraphs and community detection.

**Comment by jpfairbanks** [comment]
One approach to solving this is to retry the randomized tests because we only have false positives, that is tests that fail when the software if fine due to chance. I would like to have a function that does this rather than ad hoc solutions for every test that has this behavior. So a function like run this test until it passes or until `n` failures would be good

**Comment by jpfairbanks** [comment]
It looks like if you put a Base.Test.@test inside a try/catch block, the failure still goes on STDERR but you prevent the failing test from stopping execution. Is there a way to capture that output?

**Comment by sbromberger** [comment]
Closing this out because it's old and we've resolved most of these, plus we've moved to testsets which might have different methods.
