### ISSUE TITLE
Docs notebook

### ISSUE THREAD

**Issue by jpfairbanks** [JuliaGraphs/LightGraphs.jl#519]
This is a really good notebook introducing people to BayesNets.jl https://github.com/sisl/BayesNets.jl/blob/master/doc/BayesNets.ipynb it would be good for LG to have a similar one. This would be a great contribution for someone who uses LG or is learning it for the first time.

**Comment by sbromberger** [comment]
Agreed. It might make sense to have something like this in advance of any JuliaCon presentation :)

**Comment by juliohm** [comment]
Since I want to get closer to the current state of the project, I will try to solve this one in between my activities over the week.

**Comment by sbromberger** [comment]
@juliohm that is a great idea. Thank you for taking this on.

**Comment by ChrisRackauckas** [comment]
FYI, you might want to put it in a different repo. Notebooks will quickly become huge in a git repo because of how the history works, and you cannot do repo cleaning for Julia packages since that changes the tag sha1s. You might want to create something like [DiffEqTutorials](https://github.com/JuliaDiffEq/DiffEqTutorials.jl) to host these.

**Comment by sbromberger** [comment]
Great call, @ChrisRackauckas - thanks. Proposal to the group: new repo called `JuliaGraphsTutorials`?

**Comment by juliohm** [comment]
Awesome idea @ChrisRackauckas , thanks for sharing. @sbromberger can I move ahead and create a `JuliaGraphsTutorials` repository in the organization?

**Comment by sbromberger** [comment]
@juliohm Yes - please do. When it's created, feel free to close this issue out and open a new one in the new repo referencing this.
