### ISSUE TITLE
WIP: Abstraction

### ISSUE THREAD

**Issue by sbromberger** [JuliaGraphs/LightGraphs.jl#526]
cc @jpfairbanks @juliohm 

Abstraction to-do list:
- [x] AbstractGraphs
- [x] AbstractEdges
- [x] **PREREQUISITE: #45. If we have no benchmarks, we cannot effectively test for performance regressions.**
- [x] Decide on scaffolding for abstraction (bikeshed names, figure out hierarchy) (#527)
- [x] Determine core API contracts for LightGraphs (this will be needed for traits and to ensure that new abstractions have access to all the functionality they need for the advanced functions)
- [x] Re-implement existing Graph/DiGraph to `SimpleGraph{Int64}` (or whatever we bikeshed to)
- [ ] Change graph constructors to mirror GraphX's `Graph{VertexType, EdgeType}` with sane defaults
- [ ] Edges vs Arcs discussion

**Comment by sbromberger** [comment]
Core API:

`fadj::Vector{Vector{???}}`
`badj::Vector{Vector{???}}`
`nv::Int`
`ne::Int`
`vertices` (Iterable)
`edges` (Iterable)

**Comment by juliohm** [comment]
Thanks for cc'ing @sbromberger, can you please share more details about the proposal? I am particularly curious about the item on GraphX-like parameterization, what do we gain by supporting arbitrary vertex and edge types?

Regarding the item on an `AbstractGraph` type, I always had this question in mind when I was reading the sources, thought there was a good reason for making SimpleGraph a Union type instead of deriving directed/undirected graphs from a base type. Was it because the Julia type system wasn't quite round by the time the package started?

**Comment by sbromberger** [comment]
> what do we gain by supporting arbitrary vertex and edge types?

Flexibility, for one. LightGraphs is and always will be primarily for users who aren't graph experts. That is, their core expertise is in Biology, or Economics, or ... and they just need a way to represent their domain-specific models as a graph. That's what we do / have done very well.

LightGraphs is stable enough now that it makes sense to branch out a bit and see whether we can make the package more friendly to *developers* (vice users, above). That is, perhaps we can retool the core functions to provide a framework for other graph types.

This will never be at the expense of the original LightGraphs type, which is simple and fast for folks who aren't graph experts. That commitment will not change. Where abstracting causes regressions, we will remove the abstraction.

**Comment by juliohm** [comment]
Yes, this design will require some good thoughts and experimentation, hopefully we can make it work smoothly. One package that I came across some time ago is this one: http://julialang.org/blog/2016/08/GSoC2016-Graft

The idea is interesting, I wish the guy was contributing to the LG ecosystem instead of rewriting the whole thing from scratch as an independent package.

**Comment by sbromberger** [comment]
I was watching that GSoC project a while back. It is an interesting idea, but it's stagnated - no updates for half a year or so. We can certainly take some ideas from it though :)

**Comment by jpfairbanks** [comment]
We should add this to the README.
Lets categorize the Core API.

# Core API
These functions are defined as the public contract of the LightGraphs.AbstractGraph interface.

## Constructing and modifying the graph

> add_edge
> rem_edge
> add_vertex
> add_vertices
> rem_vertex

## Edge/Arc interface
> src
> dst

## Accessing state
> nv::Int
> ne::Int
> vertices (Iterable)
> edges (Iterable)
> neighbors
> in_edges
> out_edges
> has_vertex
> has_edge
> has_self_loops (though this might be a trait or an abstract graph type)


## Non-Core APIs
These functions can be constructed from the Core API functions but can be given specialized implementations in order to improve performance.

>fadj::Vector{Vector{???}}
> badj::Vector{Vector{???}}

I think these are an implementation detail, in_neighbors and out_neighbors are the API.
Unless you mean for other codes to implement them as a conversion routine.

> adjacency_matrix

Can be implemented from `edges(g)` or `neighbors(g,v)`

These are all core API functions

> degree

This can be computed from neighbors by default `degree(g,v) = length(neighbors(g,v))` so you don't need to implement this unless your type can compute degree faster than this method.

**Comment by sbromberger** [comment]
So, there are two types of abstraction under consideration, and I want to make sure we're talking about the same ones when we comment here.

1) Index abstraction: that is, vertices and edges can be `<: Integer` to allow for smaller graphs. For simplegraphs, this means that you can have a `Graph{UInt8}(4,5)` that will have vertices in the range of `0x1:0x4` and edges that take `UInt8`s in their data structures.

2) data abstraction: this is more ambitious and allows us to have things like `WeightedGraph` and `DictGraph`. I don't anticipate allowing arbitrary vertex indices (that is, they will always be a unitrange) but we might have to do something to index edges. This is a longer-term abstraction.

**Comment by sbromberger** [comment]
Closing this out because it's now possible to do this.
