### ISSUE TITLE
attaching visualization metadata?

### ISSUE THREAD

**Issue by stevengj** [JuliaGraphs/LightGraphs.jl#605]
When teaching, I often find myself wanting fine-grained control over graph visualization.  I want to be able to take a graph and modify labels for edges and vertices, change the colors of certain edges or vertices, etcetera.

I took a look at LightGraphs, but at first glance I didn't see any way to attach this kind of visualization metadata, ideally in a way that would easily be recognized by existing graph-visualization modules.

I ended up having to roll my own basic graph type, which was a bit annoying.  See [this notebook](http://nbviewer.jupyter.org/github/stevengj/1806-spring17/blob/master/lectures/Graphs-Networks.ipynb) for what I have in mind.

**Comment by sbromberger** [comment]
@stevengj you're right that there's not a simple way to do this. What I've done in the past (I've looked at your notebook but am not 100% sure this will work for you) is to keep the metadata indexed outside the graph structure and to write functions that access it when I need it. That is,

```
g = Graph(...)

# create vertex -> property and edge-> property maps
gprops = Vector{eltype(g)}(...)
eprops = Dict{Edge, ...}(...)

# create reverse maps (property-> vertex, property -> edge)
gpropsrev = Dict{..., eltype(g)}(...)
epropsrev = Dict{..., Edge}()
```

In my case I actually stored this in a redis database using Redis.jl, and it worked fine. One of the reasons it worked was because I wasn't relying on the property data to influence any of the graph algorithms (that is, I wasn't storing edge weights in the redis DB).

Other options you might consider:

Networks.jl
Erdos.jl

Both of those packages allow metadata to be stored and accessible.

**Comment by stevengj** [comment]
Thanks, Networks.jl, seems essentially what I want, though it looks like I would still have to implement visualization (e.g. automatically looking at a `color` attribute to color nodes and vertices) on top of that.
