### ISSUE TITLE
Regression due to unparameterized Graph - (how) should we fix?

### ISSUE THREAD

**Issue by sbromberger** [JuliaGraphs/LightGraphs.jl#617]
From #616 - it turns out that if you have a structure like
```
struct Foo
  g::Graph
end
```
you will get inference issues when you try to do anything with `Foo` that calls `Foo.g`:

```
julia> neighbors(f::Foo, v::Int) = neighbors(f.g, v)
neighbors (generic function with 3 methods)

julia> neighbors(f, 3)
5-element Array{Int64,1}:
 2
 4
 6
 7
 8

julia> @code_warntype neighbors(f,3)
```
Variables:
  #self#::LightGraphs.#neighbors
  f::Foo
  v::Int64

Body:
  begin
      return (Base.arrayref)((Core.getfield)((Core.getfield)(f::Foo, :g)**::LightGraphs.SimpleGraphs.SimpleGraph**, :fadjlist)**::Array{Array{T,1},1} where T<:Integer**, v::Int64)**::Array{T,1} where T<:Integer**
  end**::Array{T,1} where T<:Integer**

The fix, I think, is to either parameterize `g` (that is, `g:: Graph{Int}`), or fix this in LightGraphs by explicitly making `const Graph = LightGraphs.SimpleGraph.SimpleGraph{Int}`.

**Comment by sbromberger** [comment]
cc @jpfairbanks @ChrisRackauckas for some insight here.

**Comment by ChrisRackauckas** [comment]
`Graph` is an abstract type without its type parameters. It's only concrete when it's `Graph{T}`. Leaving off type parameters of any type in the type declaration will lead to issues. It's the same reason why

```julia
type BadType
  a::Vector
end
```

is a bad idea and leaks inference issues: if you don't know the type parameter, you don't know what the return values of many functions, and then inference issues come.

Parameterize it.

**Comment by sbromberger** [comment]
Many thanks, @ChrisRackauckas - I knew you'd have the answer to this. Now we just need to figure out whether or not we should redefine `Graph` to be `SimpleGraph{Int}` or rely on users to make `Graph{Int}` when they create graphs within structs. I'm sort of leaning towards the latter, since we definitely want to have `Graph` as an abstract (parameterizable) type.

**Comment by ChrisRackauckas** [comment]
`Vector` is a good example. It's parameterized, so you can do `Vector{Int}(3)`, but for many of the constructors it just infers that it should be an `Int`.

**Comment by juliohm** [comment]
I am also on this path of learning the type inference rules of Julia when it comes to parametric types. @ChrisRackauckas has been really helpful in educating me on this regard.

I believe that we should follow the convention for `Vector` here: let the user take care of parametric types explicitly. If a user is experiencing performance issues, he/she will probably know about this trick already or will open an issue, in which case we share the lessons we learned.

**Comment by sbromberger** [comment]
@juliohm As I mentioned above, I'm tending to agree with you, but this is really a regression, since in 0.7, `Graph` wasn't parameterized. It still doesn't need to be, I guess, but then we have performance issues.

In any case, if we see issues like #616 crop up again, we know what the suggested remedy will be.

**Comment by wtkranz** [comment]
Not that I am an expert on parametric types (in Julia) but let me add my observations. I think what let me astray in using `Graph` as a field type instead of `Graph{Int}` was precisely the constructor (or rather type conversion) magic: `Graph(10)` yields a `Graph{Int}` but `Graph`as a type is (to my current understanding) `Graph{<:Integer}`. Now, `Vector(10)` yields an `Array{Any, 1}` which sort of makes sense but there is no `Graph{Any}`. Moreover, I am not sure the constructor magic to choose the "right" `Integer` subtype is really what one wants. The type to enumerate the vertices sort of serves as a contract for what size graph one expects. But with the `addvertex!` method there is no reason that initial size of your graph is not exceeded at some point. I think it would make sense to always specify the type upon graph construction, i.e., only allow `Graph{Int}(10)` and not `Graph(10)`. This would also break code going from 0.5 to 0.6 and make the user think about the types explicitly

**Comment by jpfairbanks** [comment]
I agree that the existence of `addvertex!` implies to a new user that you can increase the size of the graph without fear of hitting a maximum. I think that the types other than `Graph{Int}` are for special use cases where the user is explicitly thinking about the maximum size of the graph and trying to reduce memory consumption. I would prefer a default to `Graph{Int}` rather than using the minimum type wide enough for the initial number of vertices (much like `typeof([1,2,3]) == Vector{Int})` not UInt8.

I would rather put the burden of thinking about types on the advanced user and default to doing the simplest safe thing for the novice user.

**Comment by sbromberger** [comment]
> I would rather put the burden of thinking about types on the advanced user and default to doing the simplest safe thing for the novice user.

This is my thinking as well and aligns with our "simplicity" goal. I'll go ahead and close this out, but feel free to continue the discussion.
