### ISSUE TITLE
Add support for dense graphs

### ISSUE THREAD

**Issue by LewisHein** [JuliaGraphs/LightGraphs.jl#641]
Currently LightGraphs.jl only provides types that are optimized for sparse graphs. This makes a lot of sense, but uses a lot of memory for dense graphs. As an example, a Graph(n) uses 16 bytes/edge. In theory, however, we only need 1 bit/edge for a dense graph, so the current implementation uses 128x the needed memory.

I suggest adding DenseGraph and DenseDiGraph types that store SymBitArray and BitArray adjacency matrices. I am willing work on this myself if necessary, as long as it's not too much of a time commitment.

**Comment by jpfairbanks** [comment]
We recently did a lot of work to make an AbstractGraph interface so that people could define their own graph types and get algorithms to work quickly. All you would need to do is implement a type such as

```julia
struct DenseGraph{T, S<:Integer} <: AbstractGraph
    fadj::Matrix{T}
    ne::S
end
```
which would allow weighted (T <: Real) or unweighted (T==Bool) dense graphs.

And then implement the functions in https://github.com/JuliaGraphs/LightGraphs.jl#core-api.
This will allow for all the higher level operations and analysis functions to work on your type. Of course the algorithms in this package are chosen to work on sparse graphs so they are efficient only in that case, there are usually better algorithms available for dense graphs. You will be able to chose which algorithms to specialize for dense graphs by defining new methods on the existing functions to handle the `f(g::DenseGraph, args...)` case.

**Comment by sbromberger** [comment]
@jpfairbanks is, as usual, spot on, but I'd like to add my 2 cents. This would be a great proof of concept of our work in abstraction. I could see it as a separate package that overrides the interface, and I would make the following observations:

1) initial implementation should be very quick. That is, getting the base functionality working *should* be no harder than implementing the interface.

2) optimization of higher-level functions (`adjacency_matrix` is one that comes to mind immediately) will take more time and patience.

Therefore: @LewisHein - I would encourage you to pursue this, if for no other reason than it will give you a great insight into LightGraphs' design decisions. If you do move forward, please take notes of things that you expected to be easy that weren't, and vice versa... and don't hesitate to open issues here if you run into difficulties.

Closing this out as an issue but feel free to continue the discussion here.
