### ISSUE TITLE
accessors for various structures?

### ISSUE THREAD

**Issue by sbromberger** [JuliaGraphs/LightGraphs.jl#650]
Prompted by my response here: https://stackoverflow.com/questions/44301710/julia-lightgraphs-weakly-connected-components/44424535#44424535

I think we need accessors for things like `DijkstraState` so that we don't have folks referring to attributes. Thoughts?

**Comment by jpfairbanks** [comment]
I think the bigger question is 'What is the "public API commitment" around these types?'.

If you think that the public API is the distances, parents, and predecessors then you might want to make functions for those things. If you think that everything currently in the DijstraState struct is part of that API then I think it is fine to just commit to having a struct with at least those fields.

The attributes/functions decision is less significant than the internal/external API decision.

I like the idea of a set of traversal routines returning structs that all support functions for `distances` and `parents` which are guaranteed to be `<:AbstractVector{eltype(g)}` because that is the common interface of my concept of "graph traversal". That way you could write an algorithm that is takes 

```julia
function measuresomething(g::AbstractGraph, traversal::Function, root::Integer)
    res = traversal(g, root)
    pars, dists = parents(res), distances(res)
    do_work(pars,dists)
end
```

and then swap out the traversal function to change the behavior of `measuresomething`.

For example computing eccentricity with either BFS or Dijkstra.

**Comment by sbromberger** [comment]
Yes. That's what I was thinking as well. We have `AbstractPathState` whose descendants all have `parents` and `dists` (some have other fields too, but those can be specialized). We can create an interface around those.

**Comment by sbromberger** [comment]
The problem is that `YenState` doesn't return `parents`.

**Comment by jpfairbanks** [comment]
Yeah I think that accessor functions would be good, but then we have to think about the api pretty hard

**Comment by sbromberger** [comment]
I'm closing this for now since we don't seem to have made much progress on it, and the API is pretty set.
