### ISSUE TITLE
Naming convention

### ISSUE THREAD

**Issue by sbromberger** [JuliaGraphs/LightGraphs.jl#828]
Given all the hubbub in https://discourse.julialang.org/t/naming-remove-all-underscores-to-matter-what/8549/116, I think we should have our own convention for (public/exported) identifiers.

1) if it starts with a verb, and/or it should be separate words, then use `_`.
2) if it’s directional, and/or is typically expressed as a single word, then no `_`.
3) if it should be separate words but it presents an inconsistency with related functions, then avoid the inconsistency.

so `is_directed`, `is_empty` (rule 1), but `inneighbors`, `indegree` (rule 2) and `allneighbors` (rule 3).

**Comment by sbromberger** [comment]
There's an alternate proposal by @yeesian to make all multi-word functions have underscores and to alias non-underscored names to them. We should discuss this as well.

**Comment by yeesian** [comment]
> There's an alternate proposal by @yeesian to make all multi-word functions have underscores and to alias non-underscored names to them. We should discuss this as well.

# The Proposal

The specific proposal here is to (i) always support a "canonical" underscore function name, and (ii) occasionally support aliases. So

i. `is_directed`, `is_empty`, `in_neighbors`, `in_degree` and `all_neighbors`, **and**
ii. `inneighbors`, `indegree` and `allneighbors` (subject to discussion e.g. in #823, #827)

According to the proposal, the discussion will only involve what subset of functions to include in (ii), rather than about removing functions from (i).

# Motivation

After finally catching up with the discussions you've linked me to. I just wish to point out that it reduces user-churn. I agree with James when he says that

> I think this is a lot of name churn without a clear benefit. ([source](https://github.com/JuliaGraphs/LightGraphs.jl/pull/823#issuecomment-360654228))

and

> I wish we had a better rational for deprecating the name than "to match stylistically." That is pretty disruptive. ([source](https://github.com/JuliaGraphs/LightGraphs.jl/pull/823#issuecomment-360659011))

Given that there does not seem to be a coherent principle for deciding on function names yet (else this discussion isn't necessary), I think it is premature to deprecate the function names that are being replaced (as there might be future such rounds of discussion, and the possibility of future churn), and to use aliases as a stopgap measure for supporting different naming conventions (if you so desire).

# Additional Remarks
If this proposal goes through:
- you will still need to have discussions around what subset of functions to provide additional aliases for, but
- only the canonical/underscore version can be depended upon, so it should be the one that's used in docs/internal-use.

**Comment by jpfairbanks** [comment]
What about the following decision procedure?

1. If it is two words and the first one is not {in,out}, then use an underscore.

This leads to `inneighbors, outneighbors, all_neighbors, weighted_neighbors, red_neighbors`.
I think this is consistent.

I am not bothered by the `inneighbors` but `all_neighbors` inconsistency because they are both consistent with rule 1. Of course there is an exception in that rule, but we are talking about natural language here, so there are bound to be rules with exceptions.

**Comment by sbromberger** [comment]
I've decided I'm tired of bikeshedding this issue. @jpfairbanks, we'll use your procedure.
