### ISSUE TITLE
Problem interface proposal

### ISSUE THREAD

**Issue by bovine3dom** [JuliaGraphs/LightGraphs.jl#982]
Disclaimer - @jpfairbanks came up with most of this, but the bad ideas are all mine :)

`Experimental/isomorphism.jl` is really quite long for what it does. It has 10 separate isomorphism functions:

```fish
~/.j/d/L/s/Experimental (isotypes|✔) $ rg "function.*iso.*\(g"
isomorphism.jl
33:function could_have_isomorph(g1::AbstractGraph, g2::AbstractGraph)
84:function has_induced_subgraphisomorph(g1::AbstractGraph, g2::AbstractGraph;
134:function has_subgraphisomorph(g1::AbstractGraph, g2::AbstractGraph;
184:function has_isomorph(g1::AbstractGraph, g2::AbstractGraph;
238:function count_induced_subgraphisomorph(g1::AbstractGraph, g2::AbstractGraph;
289:function count_subgraphisomorph(g1::AbstractGraph, g2::AbstractGraph;
339:function count_isomorph(g1::AbstractGraph, g2::AbstractGraph;
395:function all_induced_subgraphisomorph(g1::AbstractGraph, g2::AbstractGraph;
455:function all_subgraphisomorph(g1::AbstractGraph, g2::AbstractGraph;
521:function all_isomorph(g1::AbstractGraph, g2::AbstractGraph;
```

Having just gone through and refactored these, I can vouch for the fact that they share a lot of internal code.

I think these functions can be split up into three parts - the kind of result we want: `count,has,all`, the kind of problem: `whole,inducedsubgraph,subgraph`, and the algorithm to be used (done in #981).

A sketch of a possible solution is as follows:

```julia
abstract type GraphProblem{G} where G <: AbstractGraph end
abstract type IsomorphismProblem{G} <: GraphProblem{G} end

struct SubgraphIsomorphismProblem{G,T} <: IsomorphismProblem{G} 
    g1::G
    g2::G
    kwargs::T
end

struct InducedSubgraphIsomorphismProblem{G,T} <: IsomorphismProblem{G} 
    g1::G
    g2::G
    kwargs::T
end

p = SubgraphIsomorphismProblem(g,g)

any(p, alg::IsomorphismAlgorithm) # replace has_*
size(p, alg::IsomorphismAlgorithm) # replace count_*
collect(iterate(p, alg::IsomorphismAlgorithm)) # replace all_*
```

I'm really not sure about the names of the three functions.

---

If this pattern works well, it could be extended quite easily to other parts of LightGraphs where people might want to use heavy-duty algorithms to solve e.g, things to do with paths.

**Comment by simonschoelly** [comment]
`any`, `size` and `iterate` are all functions that are already defined for other argument types, so I think they should do roughly the same for graph problems. `any` seems to be a good name. `size` usually only works for Arrays and returns a tuple, therefore I  think it would be better to use the name `count` that usually returns a number.
For a vector you have
```
> iterate([1,2,3,4])
(1, 2)
```
so this does something completely different. I don't have a good idea for a name though. Maybe `elements`, `generate` or `MatchingIterator` ?

**Comment by bovine3dom** [comment]
Another benefit to this kind of interface is that we can have mutating versions of the functions, such as `collect!(p,alg)`, which could store the results somewhere in `p` making subsequent calls to, e.g. `count` quicker.

When I thought of these `!` versions a few minutes ago I thought it was a great idea, but now I am less sure. There's probably some non-trivial use case where it does make sense... I just can't think of it now.

@simonschoelly, I agree that `any` and `count` are good names. I'm as unconvinced as you are about `collect`/`iterate`.

Do you agree that it would be nice to have fewer functions? Does this proposal look like an improvement to you?

**Comment by jpfairbanks** [comment]
As represented as a table

|function|Description|
|--------|-----------|
|any| is there a match |
|count| how many matches |
|enumerate| iterate over a sequence of matches |
|**Type** | **Description** |
|IsomorphismProblem | Is there a bijection between vertices of `V(g)` and `V(h)` preserving all edges |
|InducedSubgraphIsomorphismProblem | Subset `g'` of vertices of `g` so that `g'` is isomorphic to `h`|
|SubgraphIsomorphismProblem | Subset `g'` of edges of `g` so that `g'` is isomorphic to `h`|
|TopologicalIsomorphismProblem | Subset `g'` topologically of `g` so that `g'` is isomorphic to `h`|


For Paths we can build a system for shortest path problems.

|Type|Description|
|--------|-----------|
|PathProblem| Generic Path Problem|
|BFSProblem | Breadth First Search|
|DFSProblem| Depth First Search|
|DijkstraProblem| Weighted Single Source Shortest Path|
|FWProblem |  All Pairs Shortest Path|
|BCProblem| Betweenness Centrality Problem|

where the interface is:
1. `srcs(p::PathProblem)` Iterator over source vertices
2.  `dsts(p::PathProblem)` Iterator over destination vertices

Now that compiler performance is better we can resurrect the visitor based traversal algorithms. We can define 

VisitorAlgorithm <: of Algorithm

where the interface is

`vopen!(state, g::AbstractGraph, v::Integer)`
`vvist!(state, g::AbstractGraph, v::Integer)`
`vclose!(state, g::AbstractGraph, v::Integer)`

Then the primary function of LG would be `solve!(p::Problem, a::Algorithm)`

**Comment by simonschoelly** [comment]
I think `enumerate` is not the best name, as it already has some kind of purpose in the Julia library. That is, we have
```
julia> collect(enumerate(['a' 'b' 'c']))
1×3 Array{Tuple{Int64,Char},2}:
 (1, 'a')  (2, 'b')  (3, 'c')

```

Is `TopologicalIsomorphismProblem` referring to topological graph minors?

**Comment by jpfairbanks** [comment]
I agree on enumerate. maybe we just implement the iterator interface and then `collect` and `enumerate` would work as expected.

Yes I was thinking of topological graph minors. I guess you wouldn't call that an isomorphism, `TopologicalMinorProblem` would work there too.

**Comment by simonschoelly** [comment]
From looking at the cycle algorithms, I think these might also be a good fit for such an interface.

**Comment by bovine3dom** [comment]
Has anyone been working on this? I have some spare time tomorrow so I was thinking of looking into it.

**Comment by bovine3dom** [comment]
I was even working on this yesterday - https://github.com/bovine3dom/LightGraphs.jl/tree/problem-interface : )

Don't look at that branch unless you want to see a lot of commented out code.

**Comment by simonschoelly** [comment]
Some premature code review:
Stuff such as `(typeof(problem) == IsomorphismProblem ` could be replaced with `problem isa IsomorphismProblem`

Also you seem to replace structs such as `struct SubGraphIsomorphismProblem <: GraphMorphismProblem end` with structs that have actual data. This is a bit of a problem with the vf2 algorithm, because the recursive algorithm copies this structure for every function. You might use a `mutual struct` instead, or change the vf2 algorithm, such that it does not to pass this struct for every function call.
I've seen that you mention a stack overflow in some comment, this could be the reason for it.

In the future we might actually replace the recursive algorithm with an iterative one, then that problem will disappear of course.

**Comment by bovine3dom** [comment]
Ah, I thought that typeof stuff was a bit ugly. Thanks.

I'll look into the copying.

The stack overflow is perhaps my fault from the previous refactoring - 

```
function has_isomorph(blah;keywords=default)
    has_isomorph(blah; keywords)
...
```

If the second line doesn't find a more specialised function it will just hammer itself. Which seems like poor design on my part - you'll only get a stack overflow if you try to use an broken implementation of the interface, but it isn't a very friendly error. The function seems to exist only to define the interface and provide documentation (in which case it could be a stub), and to provide defaults. I should probably think about it some more.

**Comment by bovine3dom** [comment]
I still think this is a good idea. It'll just take me a while to get around to it.
